/*
ls          = Lista arquivos e pastas no diretório atual
cd <diretório> = Muda para o diretório especificado
cd ..       = Volta um nível no diretório
cd -        = Volta para o diretório anterior
cd /        = Volta para o diretório raiz
cd ~        = Volta para o diretório home do usuário
pwd         = Mostra o caminho completo do diretório atual
mkdir       = Cria um novo diretório
touch       = Cria um novo arquivo vazio
rm          = Remove arquivos ou diretórios (cuidado!)
rm -r       = Remove diretórios e seus conteúdos
rmdir       = Remove diretórios vazios
mv <origem> <destino> = Move um arquivo ou diretório
mv <nome_antigo> <nome_novo> = Renoeia um arquivo ou diretório
nano        = Abre o editor de texto Nano
vim         = Abre o editor de texto Vim
cat         = Mostra o conteúdo de um arquivo
cp          = Copia arquivos ou diretórios
cp <origem> <destino> = Copia um arquivo ou diretório
cp -r       = Copia diretórios de forma recursiva
rm -rf      = Remove arquivos ou diretórios de forma recursiva e forçada (cuidado!)
git clone <link>  = Clona um repositório remoto para sua máquina local
git add     = Adiciona arquivos ao staging do Git (prepara para commit)
git commit  = Salva as alterações no histórico do Git
git commit -m "<mensagem>" = Salva as alterações com uma mensagem descritiva
git push    = Envia os commits locais para o repositório remoto
git pull    = Atualiza o repositório local com as alterações do remoto
git status  = Mostra o status do repositório (arquivos modificados, não rastreados, etc.)
git log     = Mostra o histórico de commits
git log --oneline = Mostra o histórico de commits em uma linha
git diff    = Mostra as diferenças entre o repositório local e o remoto
git diff <commit1> <commit2> = Mostra as diferenças entre dois commits
code        = Abre arquivos ou pastas no Visual Studio Code
git branch  = Lista todas as branches do repositório
git branch <nome-da-branch> = Cria uma nova branch
git branch -d <nome-da-branch>  = Remove uma branch local (se já foi mesclada)
git branch -D <nome-da-branch>  = Força a remoção de uma branch local
git checkout = Muda para uma branch específica
git revert  = Cria um commit que desfaz as alterações de um commit anterior
git push origin --delete = Remove uma branch do repositório remoto
*/